# Enable C++ support
language: cpp

# Compiler selection
matrix:
  include:
    - os: linux
      compiler: gcc

    - os: osx
      osx_image: xcode10
      addons:
        homebrew:
          packages: [ icu4c ]
      compiler: clang
      env: [ICU_ROOT=/usr/local/opt/icu4c]

# Build steps
script:
  - ./init.sh
  - mkdir build
  - cd build
  - cmake .. && cmake --build . --config Release
  - ctest -C Release -V
