# Enable C++ support
language: cpp

# Compiler selection
matrix:
  include:
    - os: linux
      compiler: gcc
      env: [CXX_STANDARD=11]

    - os: osx
      osx_image: xcode10
      addons:
        homebrew:
          packages: [ icu4c ]
      compiler: clang
      env:
        - CXX_STANDARD=11
        - ICU_ROOT=/usr/local/opt/icu4c

# Build steps
script:
  - ./init.sh
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_STANDARD=${CXX_STANDARD} ${CMAKE_OPTIONS}
  - cmake --build . --config Release
  - ctest -C Release -V
