# Enable C++ support
language: cpp

# Compiler selection
matrix:
  include:
    - os: linux
      compiler: gcc
      env: [CXX_STANDARD=11]

# Build steps
script:
  - ./init.sh
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_STANDARD=${CXX_STANDARD} ${CMAKE_OPTIONS}
  - cmake --build . --config Release
  - ctest -C Release -V
