# Enable C++ support
language: cpp

# Compiler selection
matrix:
  include:
    - os: linux
      compiler: gcc

    - os: osx
      osx_image: xcode10
      addons:
        homebrew:
          packages: [ icu4c ]
      compiler: clang
      env: [ICU_ROOT=/usr/local/opt/icu4c]

# Codecov
# Ubuntu on Travis CI has CMake 3.12.4 installed in /usr/local/cmake-3.12.4/bin/cmake
# and added to PATH. To use newer CMake (Ubuntu 20.04 has 3.16 version), install it and
# prepend its binary directory /usr/bin to PATH.
    - os: linux
      dist: focal
      addons:
        apt:
          packages: [cmake, lcov]
      compiler: gcc
      before_script:
        - cmake --version
      after_success:
        # See: https://github.com/codecov/example-cpp11-cmake
        - lcov --capture --directory . --output-file coverage.info
        - lcov --remove coverage.info '/usr/*' '*/deps/*' '*/test/*' --output-file coverage.info
        - lcov --list coverage.info
        - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
      env:
        - CMAKE_OPTIONS=-DURL_TEST_COVERAGE=ON
        - PATH=/usr/bin:$PATH

# Build steps
script:
  - ./init.sh
  - mkdir build
  - cd build
  - cmake .. ${CMAKE_OPTIONS} && cmake --build . --config Release
  - ctest -C Release -V
