name: CI on Linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: init dependances
      run: ./init.sh
    - name: cmake
      run: cmake -S . -B build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_STANDARD=20
    - name: build
      run: cmake --build build --config Release
    - name: test
      run: cd build ; ctest -C Release -V
