name: CI on Linux

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: clang++ C++20
            cxx_compiler: clang++
            cxx_standard: 20
            cmake_options: ""

          - name: clang++ C++17 with sanitizer
            cxx_compiler: clang++
            cxx_standard: 17
            cmake_options: "-DURL_TEST_SANITIZER=ON"

    steps:
    - uses: actions/checkout@v2
    - name: init dependances
      run: ./init.sh
    - name: cmake
      run: cmake -S . -B build -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }} -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} ${{ matrix.cmake_options }}
    - name: build
      run: cmake --build build --config Release
    - name: test
      run: cd build ; ctest -C Release -V
