name: Windows

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - name: VS 2019 C++20
            generator: "Visual Studio 16 2019"
            cxx_standard: 20
            cmake_options: ""

    steps:
    - uses: actions/checkout@v2
    - name: init dependances
      run: init.bat
      shell: cmd
    - name: install ICU library
      run: |
        mkdir C:\LIB
        mkdir C:\LIB\ICU
        curl -fsSL -o C:\LIB\icu4c-bin.zip https://github.com/unicode-org/icu/releases/download/release-68-1/icu4c-68_1-Win64-MSVC2019.zip
        7z x C:\LIB\icu4c-bin.zip -oC:\LIB\ICU
      shell: cmd
    - name: cmake
      run: cmake -S . -B build -G "${{ matrix.generator }}" -A x64 -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} -DICU_ROOT=C:\LIB\ICU ${{ matrix.cmake_options }}
    - name: build
      run: cmake --build build --config Release
    - name: test
      run: |
        set PATH=%PATH%;C:\LIB\ICU\bin64
        cd build
        ctest -C Release -V
      shell: cmd
