name: macOS

on:
  push:
    branches: [ main ]
    paths-ignore: [ 'doc/**', '**.md' ]
  pull_request:
    paths-ignore: [ 'doc/**', '**.md' ]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - name: clang++ C++17
            cxx_compiler: clang++
            cxx_standard: 17
            cmake_options: "-DUPA_BUILD_BENCH=ON"
            after_test: |
              build/bench-url test/wpt/urltestdata.json

    steps:
    - uses: actions/checkout@v4
    - name: install ICU library
      run: brew install icu4c
    - name: get dependencies
      run: ./init.sh
    - name: set ICU_ROOT
      run: echo "ICU_ROOT=$(if [ "${{ runner.arch }}" = "ARM64" ]; then echo '/opt/homebrew/opt/icu4c'; else echo '/usr/local/opt/icu4c'; fi)" >> $GITHUB_ENV
    - name: cmake
      run: cmake -S . -B build -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }} -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }} ${{ matrix.cmake_options }}
    - name: build
      run: cmake --build build --config Release
    - name: test
      run: ctest --test-dir build -C Release -V
    - name: after test
      if: ${{ matrix.after_test }}
      run: ${{ matrix.after_test }}
